"""Init

Revision ID: 0f3711f60db7
Revises: 
Create Date: 2026-07-27 14:58:29.475298

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0f3711f60db7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cad_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('entity_counts', sa.JSON(), nullable=True),
    sa.Column('layers', sa.JSON(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('ai_risk_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cad_changes_commit_sha'), 'cad_changes', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_cad_changes_filename'), 'cad_changes', ['filename'], unique=False)
    op.create_index(op.f('ix_cad_changes_id'), 'cad_changes', ['id'], unique=False)
    op.create_index(op.f('ix_cad_changes_pr_number'), 'cad_changes', ['pr_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cad_changes_pr_number'), table_name='cad_changes')
    op.drop_index(op.f('ix_cad_changes_id'), table_name='cad_changes')
    op.drop_index(op.f('ix_cad_changes_filename'), table_name='cad_changes')
    op.drop_index(op.f('ix_cad_changes_commit_sha'), table_name='cad_changes')
    op.drop_table('cad_changes')
    # ### end Alembic commands ###
